openapi: 3.0.0
info:
  title: Virtual Careers Fair API
  description: API documentation manually generated.
  version: 1.0.0
basePath: /
paths:
  /register:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses: 
        '201':
          description: Created